### ISSUE TITLE
How to reference CSS class to active component tab?

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul-web#1]
https://github.com/qaul/qaul-web/blob/e5c1b5fee6fc894d34b645b6c6fa982dae89c1ab/app/components/nav-bar/styles.css#L19

@luxferresum How can I reference the .active class from the component from within the component's CSS file?

**Comment by luxferresum** [comment]
@MathJud in general I recommend against using tag-names in the css file, because this way you loose some of the benefits of ECM.

You have two options:

# The `:global()` pseudo class

you can replace `.active` by [`:global(.active)`](https://github.com/salsify/ember-css-modules#global-classes). However you loose the local-binding then. So if you call a sub-component inside the `.nav-bar` tag, this will be active for all links in this sub component.

However with your current use `.nav-bar a` this is already a problem.
I would recommend to replace every call to `.nav-bar a` with a new class, like `.nav-bar-link`, and then change your `{{#link-to "bar"}}` to `{{#link-to "bar" local-class="nav-bar-link"}}`. Then you can do `.nav-bar-link:global(.active)` inside your css file.

# Override the `activeClass`

[You can [override the `activeClass`] with your own class.](https://emberjs.com/api/ember/2.18/classes/Ember.Templates.helpers/methods/link-to?anchor=link-to) With this you can do `{{#link-to "bar" activeClass=(local-class 'nav-bar-link-active')}}`, and then use `.nav-bar-link-active` inside your css. you could even call it active again, it will be the local namespaced version of active then.

**Comment by MathJud** [comment]
@luxferresum  worked out perfectly
